version: '3'
services:
  tail_back:
    build: ./api
    container_name: tail_back
    environment:
      - PYTHONUNBUFFERED=True
    restart: on-failure
    volumes:
      - ./api:/api/api
    depends_on:
      - tail_db
    ports:
      - "5000:5000"
    command: gunicorn -b 0.0.0.0:5000 -w 4 app_runner:app
  tail_front:
      build: ./app
      container_name:  tail_front
      environment:
        - PYTHONUNBUFFERED=True
      restart: on-failure
      volumes:
        - ./app:/app/app
      depends_on:
        - tail_back
      ports:
        - "80:8000"
      links:
        - tail_back:back
      command:  gunicorn -b 0.0.0.0:8000 -w 4 app_runner:app
  tail_db:
      container_name: tail_db
      image: postgres:12
      restart: on-failure
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }